name: named_mode
description: A library to translate class name, variable name and file name into other named mode easily.
version: 1.0.1
homepage: https://github.com/Arxing/dart-named_mode
author: Arxing <meiswind711108@gmail.com>

environment:
  sdk: '>=2.2.0 <3.0.0'

#dependencies:
#  path: ^1.4.1

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
